# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 954dc8e67a2df84e38320afc5ed654753d48a6af56dda40fb4e89f94952020cc4f6f7e8b9f4122870e1f8a1b40e0a8d6949e455f7e2e47eb6b2551a1e769e83a

test:
  secret_key_base: 4b81e9197b8aef957a347e6c289daadfa04a6f995a95701e39f4185cd18a76cfb05ab27d9cd5ee5cb2d0423c7ad8feede9e25e43a39b76d485b267e2235e0238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
